# Generated by Django 2.2.1 on 2019-11-28 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carrera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('apellidos', models.CharField(max_length=254)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=254)),
                ('direccion', models.CharField(max_length=254)),
                ('delete', models.BooleanField(default=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrera.Carrera')),
            ],
            options={
                'db_table': 'Alumno',
            },
        ),
    ]
