# Generated by Django 2.2.1 on 2019-12-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='delete',
        ),
    ]
